version = 1
id = "c733b405056ef6d6f6b30806"
created = "2026-09-03T19:38:41.586462306+09:00"

[trigger]
name = "mochiOS/Installer.app"
path = "applications/installer"
repository = "/home/jnix/mochiOS/applications/installer"
head = "fd5841c2a47055b2ebac218e65e65d65e78a9334"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "Refresh Installer dependency lockfile"

[[projects]]
name = "mochiOS/mBoot"
path = "mboot"
head = "11c5486f283df1432d89dc5638ea9e3208d41c9b"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "888b6c3f6ed39987596ad5709db2a5fa04b86b1a"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "11d9e9c302ae2df7a1975e6499d1d794a0760bd7"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "a194c9754b9bf67c3714858c85de3ec655be74e6"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "76ec6c3165eef8429f9157373159f0794cb18c3a"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "6b2a6bc3bd6a378e7552bc259f35e704118ec6b7"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "349d5519d5370c4b3a079404b968589daf849fd8"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "cb52345fa7f01bb0942741a0e843e39037e371e2"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "33d9c01afe745cd98dfa868a5582aa41256f40ee"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "8ca734dfba9be0388b2a4fc24a443580ee654753"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "e11e4b59d4121dd50cc2d2a2aa7c6ad715d719b0"

[[projects]]
name = "mochiOS/Installer.app"
path = "applications/installer"
head = "fd5841c2a47055b2ebac218e65e65d65e78a9334"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "c4f1ebf675acd4f7e38330c9f9d64cd5718da239"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "faf13aaa596e676668a5485f29ee3ec9d5223a9e"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "2d6d2340343f7ab10452b483d855da984087af8e"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "2e1f8c55245394ca9909a7d400545cb961d177b7"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "3070d37501be228621175b915274a84e84bd23d7"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "bf8b63de54a1e85a4fb2d2370a18b310cb02491a"

[[projects]]
name = "mochiOS/Settings.app"
path = "applications/settings"
head = "40bbf56bbe50c696afd8788eed1dcc76410ca5db"
